"""Add WasteLot

Revision ID: aafdd4a447fb
Revises: 9c2022cdecda
Create Date: 2026-06-23 21:19:22.025873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafdd4a447fb'
down_revision: Union[str, Sequence[str], None] = '9c2022cdecda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_identifier', sa.String(), nullable=True),
    sa.Column('generator_id', sa.Integer(), nullable=True),
    sa.Column('recycler_id', sa.Integer(), nullable=True),
    sa.Column('material_category', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('quality_grade', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generator_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['recycler_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_lots_id'), 'waste_lots', ['id'], unique=False)
    op.create_index(op.f('ix_waste_lots_lot_identifier'), 'waste_lots', ['lot_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_lots_lot_identifier'), table_name='waste_lots')
    op.drop_index(op.f('ix_waste_lots_id'), table_name='waste_lots')
    op.drop_table('waste_lots')
    # ### end Alembic commands ###
