"use client";

import React, { useRef } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { Trash2, Scan, Activity, Database, Handshake, Factory } from 'lucide-react';

export default function MarketplaceHowItWorks() {
  const containerRef = useRef<HTMLDivElement>(null);

  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end end"]
  });

  // Translate horizontal container based on vertical scroll
  // We want to move from 0 to something like -66% (if 300vw) or -75% (if 400vw)
  // We have 6 steps. 300vw is probably good.
  const x = useTransform(scrollYProgress, [0, 1], ["0%", "-66.66%"]);
  
  // Progress line that fills up based on scroll
  const lineScaleX = useTransform(scrollYProgress, [0, 0.9], [0, 1]);

  const steps = [
    { icon: <Trash2 />, title: "Generate Waste", desc: "Materials are generated by institutions or industries." },
    { icon: <Scan />, title: "AI Verification", desc: "ForEVAR's intelligence layer identifies every material." },
    { icon: <Activity />, title: "Quality Score", desc: "Purity and contamination levels are mathematically scored." },
    { icon: <Database />, title: "Listed on Exchange", desc: "Verified materials enter the trusted marketplace." },
    { icon: <Handshake />, title: "Matched with Recycler", desc: "Transactions occur based on verified data, not guesswork." },
    { icon: <Factory />, title: "Recovered into New Material", desc: "Waste re-enters the economy as a valuable resource." }
  ];

  return (
    <section ref={containerRef} className="relative w-full h-[400vh] bg-[#050505]">
      
      <div className="sticky top-0 w-full h-screen overflow-hidden flex flex-col justify-center bg-[#050505] border-t border-white/5">
        
        <div className="absolute top-24 left-12 lg:left-24 z-20">
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-heading font-bold tracking-tighter text-white">
            One Simple <span className="text-accent-primary">Recovery Journey.</span>
          </h2>
        </div>

        {/* The extremely wide content container */}
        <motion.div style={{ x }} className="flex h-full w-[300vw] relative items-center px-[10vw]">
          
          {/* Background Connecting Line */}
          <div className="absolute top-1/2 left-[10vw] right-[10vw] h-[2px] bg-white/10 -translate-y-1/2 z-0" />
          
          {/* Active Connecting Line */}
          <motion.div 
            style={{ scaleX: lineScaleX, originX: 0 }}
            className="absolute top-1/2 left-[10vw] right-[10vw] h-[2px] bg-gradient-to-r from-accent-primary to-[#3B82F6] -translate-y-1/2 z-0" 
          />

          <div className="flex w-full justify-between relative z-10">
            {steps.map((step, index) => (
              <div key={index} className="flex flex-col items-center group w-[250px]">
                
                <div className="text-text-secondary font-mono text-sm tracking-widest mb-6 transition-colors duration-500 group-hover:text-white">
                  STEP 0{index + 1}
                </div>
                
                <div className="w-24 h-24 rounded-full bg-[#0A0A0A] border border-white/10 flex items-center justify-center mb-8 relative transition-all duration-500 group-hover:border-accent-primary group-hover:shadow-[0_0_30px_rgba(124,255,79,0.2)]">
                  <div className="text-white/50 group-hover:text-accent-primary transition-colors duration-500 w-10 h-10">
                    {React.cloneElement(step.icon as React.ReactElement, { className: "w-full h-full" })}
                  </div>
                  <div className="absolute inset-2 rounded-full border border-dashed border-white/5 group-hover:border-accent-primary/20 animate-spin-slow" />
                </div>
                
                <h3 className="text-xl font-heading font-bold text-white mb-4 text-center">
                  {step.title}
                </h3>
                
                <p className="text-sm text-text-secondary font-body font-light text-center leading-relaxed">
                  {step.desc}
                </p>
                
              </div>
            ))}
          </div>

        </motion.div>

      </div>
    </section>
  );
}
